resource/aws_codebuild_project: Deprecate source and secondary_sources auth blocks
Reference: https://docs.aws.amazon.com/codebuild/latest/APIReference/API_SourceAuth.html
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/13450

Currently, the following consistent test failure occurs in AWSCodeBuildProject acceptance testing:

```
--- FAIL: TestAccAWSCodeBuildProject_Source_Auth (11.50s)
    testing.go:683: Step 1 error: errors during apply:

        Error: Error creating CodeBuild project: InvalidInputException: No Access token found, please visit AWS CodeBuild console to connect to GitHub
```

The API documentation now very explicitly states this underlying API type is deprecated. Here we mark the block and underlying attributes as deprecated suggesting the `aws_codebuild_source_credential` resource and removing the problematic test rather than temporarily introducing a skipping mechanism.